config/routes.rb
Rails.application.routes.draw do
  resources :advertisements

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :users, only: [:new, :create]
  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'faq' => 'welcome#faq'

  root to: 'welcome#about'
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  has_many :comments, dependent: :destroy

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic :SponsoredPost
  has_many :topics
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

  has_secure_password
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisements = Advertisement.find(params[:id])
  end

  def new
    @advertisements = Advertisement.new
  end

  def create
    @advertisements = Advertisement.new
    @advertisements.title = params[:advertisement][:title]
    @advertisements.copy = params[:advertisement][:copy]
    @advertisements.price = params[:advertisement][:price]

    if @advertisement.save
      flash[:notice] = "Advertisement was saved."
      redirect_to @advertisements
    else
      flash[:error] = "There was an error saving the advetisement. Please try again."
      render :new
  end
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create

    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])

    @post.topic = @topic

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
      @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
   @post = Post.find(params[:id])

     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to [@post.topic, @post]
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
   end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @question = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params.require(:question).permit(:title, :body, :resolved))
    if @question.save
      flash[:notice] = "Question was saved"
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(parms.require(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{question.title}\" was deleted successfully."
      redirect_to question_path
    else
      flash[:error] = "There was an error deleting the question."
      render :show
    end
  end
end

app/controllers/sponsored_post_controller.rb
class SponsoredPost < ApplicationController

  def show
    @sponsored_posts = SponsoredPost.find(params[:id])
  end

  def new
    @sponsored_posts = SponsoredPost.find(params[:topic_id])
    @sponsored_posts = SponsoredPost.new
  end

  def edit
      @sponsored_posts = SponsoredPost.find(params[:id])
  end
end

app/controllers/sponsoredpost_controller.rb
class SponsoredPost < ApplicationController

  def show
    @sponsored_posts = SponsoredPost.find(params[:id])
  end

  def new
    @sponsored_posts = SponsoredPost.find(params[:topic_id])
    @sponsored_posts = SponsoredPost.new
  end

  def edit
      @sponsored_posts = SponsoredPost.find(params[:id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new
    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.name = params[:topic][:name]
    @topic.description = params[:topic][:description]
    @topic.public = params[:topic][:public]

    if @topic.save
        flash[:notice] = "Topic was updated."
        redirect_to @topic
    else
        flash.now[:alert] = "Error saving topic. Please try again."
        render :edit
    end
  end

  def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def form_group_tag(errors, &block)
      css_class = 'form-group'
      css_class << ' has-error' if errors.any?

      content_tag :div, capture(&block), class: css_class
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/create.html.erb
<h1>Advertisements#create</h1>
<p>Find me in app/views/advertisements/create.html.erb</p>

app/views/advertisements/index.html.erb
<h1>Advertisements</h1>
<% @advertisements.each do |ad| %>

  <div class="media" >
    <div class="media-body" >
      <h4 class="media-heading" >
        <%= link_to "$#{ad.price}: #{ad.title}", ad %>
      </h4>
    </div>
  </div>
<% end %>

app/views/advertisements/new.html.erb
<h1>New Advertisements</h1>

<div class="row">
  <% form_for @advertisement do |f|
    <div class="form-group">
      <% f.label :title %>
      <% f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    </div>

    <div class="form-group">
      <% f.label :copy %>
      <% f.text_area :copy, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    </div>

    <div class="form-group">
      <% f.label :price %>
      <% f.text_field :price, class: 'form-control', placeholder: 99 %>
    </div>

    <div class="form-group">
      <% f.label :title %>
      <% f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/advertisements/show.html.erb
<h1><%="$#{@advertisement.price}: #{@advertisement.title}" %></h1>
<p><%= @advertisement.copy%></p>

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>

    <% if post.errors.any? %>

      <div class="alert alert-danger">

        <h4><%= pluralize(post.errors.count, "error") %>.</h4>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>

        <%= form_group_tag(post.errors[:body]) do %>
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

    <div class="alert alert-danger">

      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">

     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>

       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>

       <div class="form-group">
         Mark as Resolved? <%= f.check_box :resolved%>
       </div>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>

   </div>
 </div>

app/views/posts/index.html.erb
<h1>All Questions</h1>

 <% @questions.each do |question| %>
     <div class="media">
       <div class="media-body">
         <h4 class="media-heading">
           <%= link_to question.title, question %>
         </h4>
       </div>
     </div>
 <% end %>

app/views/posts/new.html.erb
 <h1>New Post</h1>

 <div class="row">
   <div class="col-md-4">

     <p>Guidelines for questions</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>

   <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<h1><%= @question.title %></h1>

  <div class="row">
    <div class="col-md-8">
      <p><%= @question.body %></p>
    </div>

    <h1><%= @question.title %></h1>
    <p><%= @question.body %></p>
    <p><%= @question.resolved %></p>

   <div class="col-md-4">
     <%= link_to "Edit", edit_question_path(@post), class: 'btn btn-success' %>
     <%= link_to "Delete Question", @pquestion, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question?'} %>
   </div>
 </div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>

      <div class="form-group">
        <% f.label :resolved %>
        <% f.check_box :resolved %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>Questions index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
      </div>

      <div class="form-group">
        <% f.label :resolved %>
        <% f.check_box :resolved %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p><%= @question.resolved %></p>

<div class="cold-md-4">
  <% link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
  <% link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to selete this question?'} %>
</div>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if topic.errors.any? %>
    <div class"alert alert-danger?
      <h4>There are <%pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
          <% topic.errors.full_messages.each do |msg| %>
            <li<% msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
  <% end %>
  <div class="form-group">
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

 <div class="row">
   <div class="col-md-8">

     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>

 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>

     <% @topic.posts.each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
              <%= link_to post.title, topic_post_path(@topic, post) %>
           </h4>
           <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago <br>
             <%= post.comments.count %> Comments
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Post away!</h1>
<p>by Heda Hahn</p>

<button class="social-btn"><%= link_to "Follow me", "https://www.facebook.com/trybloc"%></button>
<button class="social-btn"><%= link_to "Contact me", "http://www.hedahahn.com/#!contact/c1et"%></button>

app/views/welcome/contact.html.erb
<h1>Contact Heda</h1>
<p>Come follow me!</p>

<button class="social-btn"><%= link_to "Find me", "http://www.hedahahn.com/#!contact/c1et"%></button>

app/views/welcome/faq.html.erb
<h1>Welcome to Bloccit</h1>
<p id="index-title">This is the home page for Bloccit.</p>
<div class="posts">Welcome to my application.</div>
<div class="posts">Post here.</div>
<section>This is the content in a section element.</section>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p id="index-title">This is the home page for Bloccit.</p>
<div class="posts">Post 1 goes here.</div>
<div class="posts">Post 2 goes here.</div>
<section>I am the content in a section element.</section>